Repository jj1976/SSW555AgileMethodsCJBS, pull requests merged in 2018-02, with the labels that each got.

#21 Adding Note to the test file. Also fixed docstring in the parser.
  GedcomParser.py
  sampledata/ccorradop02test.ged
Labels: feature

#23 Adding Gender For Role Code and Tests
  GedcomParser.py
  GedcomParserTests.py
  GenderForRoleTests.py
  models/Individual.py
  sampledata/us21testdata.ged
Labels: feature

#26 US25 #time 2h #comment Wrote validator function for children in Fam
  GedcomParser.py
  UniqueNameBirthdateTests.py
  models/Family.py
  models/Individual.py
  sampledata/us25testdata.ged
Labels: feature

#25 Feature/us23 unique name and birth date
  GedcomParser.py
  UniqueNameBirthDateTests.py
  sampledata/US23_test_data_tara_twice_vincent_&_arlette_bdate.ged
Labels: feature

#31 US38 Completed
  GedcomParser.py
  models/Individual.py
  sampledata/US22unique_FAM_ID_tst.ged
  sampledata/US22unique_ID_tst.ged
  sampledata/US23_test_data_tara_twice_vincent_&_arlette_bdate.ged
  sampledata/US23unique_birth_tst.ged
  sampledata/US23unique_name_tst.ged
  tests/GedcomTests.py
  tests/testGedcomParser.py
  tests/testGenderForRole.py
  tests/testUniqueNameBirthDate.py
Labels: feature

#34 Add Unit Tests for US 38
  GedcomParser.py
  models/Individual.py
  tests/testUpcomingBirthdays.py
Labels: enhancement

#24 Changes US01 and US02 into the restructured file
  GedcomParser.py
  README.md
  TeamSSW55AgileMethodsCJBS_Report.xlsx
  models/Family.py
  models/Individual.py
  models/Member.py
  sampledata/US01futuredatestests.ged
  tests/testGedcomParser.py
  tests/testGenderForRole.py
  tests/testIndividualFamilyDates.py
Labels: feature

#30 US10 Wrote a few unit tests to validate the marriage method.
  GedcomParser.py
  models/Family.py
  sampledata/US01futuredatestests.ged
  sampledata/US21NegTestData.ged
  sampledata/us10testdata.ged
  tests/UserMarriageDateTests.py
  tests/testGedcomParser.py
  tests/testGenderForRole.py
Labels: bug

#36 Travis Tests (+11 squashed commit)
  .travis.yml
  GedcomTests.py
  requirements.txt
  sampledata/US21negtestdata.ged
  tests/UserMarriageDateTests.py
  tests/testGedcomParser.py
  tests/testGenderForRole.py
  tests/testIndividualFamilyDates.py
  tests/testUniqueNameBirthDate.py
  tests/testUpcomingBirthdays.py
Labels: enhancement

#38 US04 and US17 changes
  models/Family.py
  models/Individual.py
  sampledata/us04testdata.ged
  sampledata/us17testdata.ged
  tests/testMarriageBeforeDivorce.py
  tests/testMarriageNotWithDescendants.py
Labels: feature

#39 Sprint 1 Output Generator
  GedcomParser.py
  models/Family.py
  sampledata/basetestdata.ged
  sampledata/sprint1testdata.ged
  sprint1output.txt
  tests/testGedcomParser.py
  tests/testIndividualFamilyDates.py
  tests/testSprint1.py
  tests/testUniqueNameBirthDate.py
Labels: enhancement

#41 Bugfix/us23 run method
  GedcomParser.py
  sampledata/US23unique_name_tst.ged
  sprint1output.txt
Labels: bug
